package orchestrator

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"sync"

	"github.com/fabith10/synapse-go/pkg/logger"
)

type SubTask struct {
	ID           string   `json:"id"`
	Description  string   `json:"description"`
	Dependencies []string `json:"dependencies"`
	Recipient    string   `json:"recipient"`
	Status       string   `json:"status"` // "pending", "running", "completed", "failed"
	Result       string   `json:"result"`
}

type ExecutionPlan struct {
	OriginalGoal  string              `json:"original_goal"`
	Tasks         map[string]*SubTask `json:"tasks"`
	CorrelationID string              `json:"correlation_id"`
	Mode          string              `json:"orchestration_mode"`
	Mu            sync.Mutex          `json:"-"`
}

type PlannerScheduler struct {
	plans map[string]*ExecutionPlan
	mu    sync.RWMutex
	send  func(Message)
}

var GlobalPlannerScheduler = &PlannerScheduler{
	plans: make(map[string]*ExecutionPlan),
}

func (ps *PlannerScheduler) Initialize(sendFn func(Message)) {
	ps.mu.Lock()
	defer ps.mu.Unlock()
	ps.send = sendFn
}

func extractJSON(input string) string {
	trimmed := strings.TrimSpace(input)

	// Try to find markdown code fences first
	if idx := strings.Index(trimmed, "```json"); idx != -1 {
		content := trimmed[idx+7:]
		if endIdx := strings.Index(content, "```"); endIdx != -1 {
			trimmed = strings.TrimSpace(content[:endIdx])
		}
	} else if idx := strings.Index(trimmed, "```"); idx != -1 {
		content := trimmed[idx+3:]
		if endIdx := strings.Index(content, "```"); endIdx != -1 {
			trimmed = strings.TrimSpace(content[:endIdx])
		}
	}

	// Now look for the first brace `{` or `[` and the last brace `}` or `]`
	firstBrace := strings.Index(trimmed, "{")
	firstBracket := strings.Index(trimmed, "[")

	start := -1
	end := -1

	if firstBrace != -1 && (firstBracket == -1 || firstBrace < firstBracket) {
		start = firstBrace
		end = strings.LastIndex(trimmed, "}")
	} else if firstBracket != -1 {
		start = firstBracket
		end = strings.LastIndex(trimmed, "]")
	}

	if start == -1 || end == -1 || end <= start {
		return trimmed
	}
	return trimmed[start : end+1]
}

// StartPlan parses the JSON plan text generated by planner-agent and initiates execution.
func (ps *PlannerScheduler) StartPlan(goal, planJSON, corrID string, meta map[string]string) error {
	cleanedJSON := extractJSON(planJSON)

	var parsed struct {
		OriginalGoal string             `json:"original_goal"`
		Tasks        map[string]*SubTask `json:"tasks"`
	}

	if err := json.Unmarshal([]byte(cleanedJSON), &parsed); err != nil {
		return fmt.Errorf("failed to parse task plan: %w (plan content: %s)", err, planJSON)
	}

	// If parsed tasks are empty, it might be that the model returned raw text synthesis.
	if len(parsed.Tasks) == 0 {
		return fmt.Errorf("no sub-tasks found in execution plan")
	}

	mode := "autonomous"
	if meta != nil && meta["orchestration_mode"] == "steered" {
		mode = "steered"
	}

	plan := &ExecutionPlan{
		OriginalGoal:  goal,
		Tasks:         parsed.Tasks,
		CorrelationID: corrID,
		Mode:          mode,
	}

	// Normalize initial state
	for _, t := range plan.Tasks {
		t.Status = "pending"
		t.Result = ""
	}

	ps.mu.Lock()
	ps.plans[corrID] = plan
	ps.mu.Unlock()

	logger.WithComponent("planner_scheduler").Info("Initiating plan",
		"subtask_count", len(plan.Tasks), "correlation_id", corrID, "mode", plan.Mode)

	if plan.Mode == "steered" {
		var preview string
		for id, t := range plan.Tasks {
			depsStr := ""
			if len(t.Dependencies) > 0 {
				depsStr = fmt.Sprintf(" (depends on %s)", strings.Join(t.Dependencies, ", "))
			}
			preview += fmt.Sprintf("• [%s] %s ➔ routed to %s%s\n", id, t.Description, t.Recipient, depsStr)
		}

		ps.send(Message{
			Sender:    "planner-agent",
			Recipient: "USER",
			Content:   fmt.Sprintf("[Risk Checkpoint] Review and approve execution plan for goal: %q\n\nTasks:\n%s", goal, preview),
			Metadata: map[string]string{
				"Type":           "HITL_APPROVAL",
				"correlation_id": corrID,
				"reply_to":       "planner-agent",
				"risk_level":     "MEDIUM",
				"action":         "plan.execute",
			},
		})
		return nil
	}

	ps.dispatchReadyTasks(plan)
	return nil
}

// ExecutePlan starts a steered plan after user hits approve.
func (ps *PlannerScheduler) ExecutePlan(corrID string) {
	ps.mu.RLock()
	plan, exists := ps.plans[corrID]
	ps.mu.RUnlock()

	if !exists {
		return
	}

	logger.WithComponent("planner_scheduler").Info("Plan approved by user, starting execution", "correlation_id", corrID)
	ps.send(Message{
		Sender:    "planner-agent",
		Recipient: "USER",
		Content:   "[Plan Execution] Plan approved by user. Dispatching initial tasks...",
		Metadata: map[string]string{
			"correlation_id":    corrID,
			"supervisor_bypass": "true",
			"Type":              "PROGRESS",
		},
	})
	ps.dispatchReadyTasks(plan)
}

// HandleSubTaskResponse is called when an agent finishes a sub-task. It updates the state machine
// and triggers the next parallel wave of independent sub-tasks.
func (ps *PlannerScheduler) HandleSubTaskResponse(ctx context.Context, subtaskID, result, corrID string) {
	ps.mu.RLock()
	plan, exists := ps.plans[corrID]
	ps.mu.RUnlock()

	if !exists {
		return
	}

	plan.Mu.Lock()
	task, ok := plan.Tasks[subtaskID]
	if ok && task.Status == "running" {
		task.Status = "completed"
		task.Result = result
		logger.WithComponent("planner_scheduler").Info("Sub-task completed", "subtask_id", subtaskID, "correlation_id", corrID)
	}
	plan.Mu.Unlock()

	ps.dispatchReadyTasks(plan)
}

func (ps *PlannerScheduler) dispatchReadyTasks(plan *ExecutionPlan) {
	plan.Mu.Lock()
	defer plan.Mu.Unlock()

	allDone := true
	dispatchedAny := false

	// Gather completed outputs to pass to synthesis phase or logs
	for _, t := range plan.Tasks {
		if t.Status != "completed" {
			allDone = false
		}

		if t.Status == "pending" {
			// Check if all dependencies are completed
			depsMet := true
			for _, depID := range t.Dependencies {
				depTask, ok := plan.Tasks[depID]
				if !ok || depTask.Status != "completed" {
					depsMet = false
					break
				}
			}

			if depsMet {
				t.Status = "running"
				dispatchedAny = true

				logger.WithComponent("planner_scheduler").Info("Dispatching sub-task", "subtask_id", t.ID, "description", t.Description)

				// Log event dynamically to SSE logs
				ps.send(Message{
					Sender:    "planner-agent",
					Recipient: "USER",
					Content:   fmt.Sprintf("[Plan Execution] Dispatched sub-task %q (Parallel Execution: %s)", t.ID, t.Description),
					Metadata: map[string]string{
						"correlation_id":    plan.CorrelationID,
						"supervisor_bypass": "true",
						"Type":              "PROGRESS",
					},
				})

				taskContent := t.Description
				ancestors := getAllCompletedAncestors(plan, t)
				if len(ancestors) > 0 {
					var depData strings.Builder
					depData.WriteString(taskContent)
					depData.WriteString("\n\nHere is the data from completed upstream dependencies you need for this task:\n")
					for _, ancestorTask := range ancestors {
						resText := strings.TrimSpace(ancestorTask.Result)
						if len(resText) > 1500 {
							resText = resText[:1500] + "\n...[truncated verbose log output]..."
						}
						depData.WriteString(fmt.Sprintf("--- Data from Task %s (%s) ---\n%s\n\n", ancestorTask.ID, ancestorTask.Description, resText))
					}
					taskContent = strings.TrimSpace(depData.String())
				}

				// Send task message to triage-agent
				go func(task *SubTask, content string) {
					ps.send(Message{
						Sender:    "planner-agent",
						Recipient: "triage-agent",
						Content:   content,
						Metadata: map[string]string{
							"correlation_id":      plan.CorrelationID,
							"is_subtask":          "true",
							"subtask_id":          task.ID,
							"subtask_description": task.Description, // Pass description!
							"original_goal":       plan.OriginalGoal,
							"goal_mode":           "true",
							"planner_bypass":      "true", // Prevent looping back to planner
							"reply_to":            "planner-agent",
						},
					})
				}(t, taskContent)
			}
		}
	}

	if allDone {
		logger.WithComponent("planner_scheduler").Info("All sub-tasks completed, generating final synthesis report", "correlation_id", plan.CorrelationID)

		// Aggregate task outputs
		var aggregated bytesOutput
		for id, t := range plan.Tasks {
			aggregated.WriteString(fmt.Sprintf("### Task: %s (%s)\nGoal: %s\nResult:\n%s\n\n", id, t.Description, t.Description, t.Result))
		}

		ps.send(Message{
			Sender:    "planner-agent",
			Recipient: "USER",
			Content:   "[Plan Execution] All sub-tasks completed. Synthesizing final report...",
			Metadata: map[string]string{
				"correlation_id":    plan.CorrelationID,
				"supervisor_bypass": "true",
				"Type":              "PROGRESS",
			},
		})

		// Send aggregate outputs back to planner-agent for final summary synthesis
		go func() {
			ps.send(Message{
				Sender:    "USER",
				Recipient: "planner-agent",
				Content:   aggregated.String(),
				Metadata: map[string]string{
					"correlation_id": plan.CorrelationID,
					"phase":          "synthesis",
					"goal":           plan.OriginalGoal,
				},
			})
		}()
	} else if !dispatchedAny {
		// Verify if we are deadlocked (e.g. some running task is active)
		hasActive := false
		for _, t := range plan.Tasks {
			if t.Status == "running" {
				hasActive = true
				break
			}
		}

		if !hasActive {
			// No active tasks and still not all done - some dependency configuration is cycle or missing
			logger.WithComponent("planner_scheduler").Error("DAG deadlock detected on plan", "correlation_id", plan.CorrelationID)
			ps.send(Message{
				Sender:    "planner-agent",
				Recipient: "USER",
				Content:   fmt.Sprintf("[Plan Stalled] A dependency cycle or missing task requirements led to a deadlock in plan %s. Execution terminated.", plan.CorrelationID),
				Metadata: map[string]string{
					"correlation_id":    plan.CorrelationID,
					"supervisor_bypass": "true",
					"Type":              "PROGRESS",
				},
			})
		}
	}
}

// Helpers

type bytesOutput struct {
	buf []byte
}

func (bo *bytesOutput) WriteString(s string) {
	bo.buf = append(bo.buf, s...)
}

func (bo *bytesOutput) String() string {
	return string(bo.buf)
}

// Middleware returns an Orchestrator middleware to intercept plan, subtask, and progress messages.
func (ps *PlannerScheduler) Middleware() MiddlewareFunc {
	return func(ctx context.Context, msg Message, next func(Message)) {
		// 1. Intercept planner-agent plan output
		if msg.Sender == "planner-agent" && msg.Recipient == "USER" && (msg.Metadata == nil || msg.Metadata["phase"] != "synthesis") {
			goal := msg.Metadata["correlation_id"]
			if msg.Metadata != nil && msg.Metadata["goal"] != "" {
				goal = msg.Metadata["goal"]
			}
			err := ps.StartPlan(goal, msg.Content, msg.Metadata["correlation_id"], msg.Metadata)
			if err == nil {
				return // Suppress sending raw JSON plan to user
			}
			logger.WithComponent("planner_scheduler").Warn("Parsing error, falling back to direct delivery", "error", err)
		}

		// 2. Intercept completed subtasks (only if they have bypassed the supervisor)
		if msg.Recipient == "USER" && msg.Metadata != nil && msg.Metadata["is_subtask"] == "true" {
			if msg.Metadata["supervisor_bypass"] == "true" {
				ps.HandleSubTaskResponse(ctx, msg.Metadata["subtask_id"], msg.Content, msg.Metadata["correlation_id"])
				return // Suppress sending raw sub-task output to user HITL
			}
		}

		// 3. Intercept progress messages to avoid blocking the orchestrator or prompting the user
		if msg.Recipient == "USER" && msg.Metadata != nil && msg.Metadata["Type"] == "PROGRESS" {
			return // Suppress sending progress updates to the human HITL channel
		}

		// Continue downstream
		next(msg)
	}
}

// getAllCompletedAncestors returns all completed predecessor tasks for a subtask in topological order.
func getAllCompletedAncestors(plan *ExecutionPlan, task *SubTask) []*SubTask {
	visited := make(map[string]bool)
	var ordered []*SubTask

	var dfs func(id string)
	dfs = func(id string) {
		t, ok := plan.Tasks[id]
		if !ok {
			return
		}
		for _, depID := range t.Dependencies {
			if !visited[depID] {
				visited[depID] = true
				dfs(depID)
				if depTask, exists := plan.Tasks[depID]; exists && depTask.Status == "completed" {
					ordered = append(ordered, depTask)
				}
			}
		}
	}

	dfs(task.ID)
	return ordered
}
